class Constants:
    LOL2REG={
        'BR1': 'br',
        'EUN1': 'eu',
        'EUW1': 'eu',
        'JP1': 'ap',
        'KR': 'kr',
        'LA1': 'latam',
        'LA2': 'latam',
        'NA1': 'na',
        'OC1': 'ap',
        'PBE1': 'na',
        'RU': 'eu',
        'TR1': 'eu'
    }

    #please contact me if u found a mistake
    COU2REG={
        "BD": "AP",
        "BE": "EU",
        "BF": "EU",
        "BG": "EU",
        "BA": "EU",
        "BB": "NA",
        "WF": "AP",
        "BL": "NA",
        "BM": "NA",
        "BN": "AP",
        "BO": "LATAM",
        "BH": "AP",
        "BI": "EU",
        "BJ": "EU",
        "BT": "AP",
        "JM": "NA",
        "BV": "AN",
        "BW": "EU",
        "WS": "AP",
        "BQ": "NA",
        "BR": "BR",
        "BS": "NA",
        "JE": "EU",
        "BY": "EU",
        "BZ": "NA",
        "RU": "EU",
        "RW": "EU",
        "RS": "EU",
        "TL": "AP",
        "RE": "EU",
        "TM": "AP",
        "TJ": "AP",
        "RO": "EU",
        "TK": "AP",
        "GW": "EU",
        "GU": "AP",
        "GT": "NA",
        "GS": "AN",
        "GR": "EU",
        "GQ": "EU",
        "GP": "NA",
        "JP": "AP",
        "GY": "LATAM",
        "GG": "EU",
        "GF": "LATAM",
        "GE": "AP",
        "GD": "NA",
        "GB": "EU",
        "GA": "EU",
        "SV": "NA",
        "GN": "EU",
        "GM": "EU",
        "GL": "NA",
        "GI": "EU",
        "GH": "EU",
        "OM": "AP",
        "TN": "EU",
        "JO": "AP",
        "HR": "EU",
        "HT": "NA",
        "HU": "EU",
        "HK": "AP",
        "HN": "NA",
        "HM": "AN",
        "VE": "LATAM",
        "PR": "NA",
        "PS": "AP",
        "PW": "AP",
        "PT": "EU",
        "SJ": "EU",
        "PY": "LATAM",
        "IQ": "AP",
        "PA": "NA",
        "PF": "AP",
        "PG": "AP",
        "PE": "LATAM",
        "PK": "AP",
        "PH": "AP",
        "PN": "AP",
        "PL": "EU",
        "PM": "NA",
        "ZM": "EU",
        "EH": "EU",
        "EE": "EU",
        "EG": "EU",
        "ZA": "EU",
        "EC": "LATAM",
        "IT": "EU",
        "VN": "AP",
        "SB": "AP",
        "ET": "EU",
        "SO": "EU",
        "ZW": "EU",
        "ES": "EU",
        "ER": "EU",
        "ME": "EU",
        "MD": "EU",
        "MG": "EU",
        "MF": "NA",
        "MA": "EU",
        "MC": "EU",
        "UZ": "AP",
        "MM": "AP",
        "ML": "EU",
        "MO": "AP",
        "MN": "AP",
        "MH": "AP",
        "MK": "EU",
        "MU": "EU",
        "MT": "EU",
        "MW": "EU",
        "MV": "AP",
        "MQ": "NA",
        "MP": "AP",
        "MS": "NA",
        "MR": "EU",
        "IM": "EU",
        "UG": "EU",
        "TZ": "EU",
        "MY": "AP",
        "MX": "NA",
        "IL": "AP",
        "FR": "EU",
        "IO": "AP",
        "SH": "EU",
        "FI": "EU",
        "FJ": "AP",
        "FK": "LATAM",
        "FM": "AP",
        "FO": "EU",
        "NI": "NA",
        "NL": "EU",
        "NO": "EU",
        "NA": "EU",
        "VU": "AP",
        "NC": "AP",
        "NE": "EU",
        "NF": "AP",
        "NG": "EU",
        "NZ": "AP",
        "NP": "AP",
        "NR": "AP",
        "NU": "AP",
        "CK": "AP",
        "XK": "EU",
        "CI": "EU",
        "CH": "EU",
        "CO": "LATAM",
        "CN": "AP",
        "CM": "EU",
        "CL": "LATAM",
        "CC": "AP",
        "CA": "NA",
        "CG": "EU",
        "CF": "EU",
        "CD": "EU",
        "CZ": "EU",
        "CY": "EU",
        "CX": "AP",
        "CR": "NA",
        "CW": "NA",
        "CV": "EU",
        "CU": "NA",
        "SZ": "EU",
        "SY": "AP",
        "SX": "NA",
        "KG": "AP",
        "KE": "EU",
        "SS": "EU",
        "SR": "LATAM",
        "KI": "AP",
        "KH": "AP",
        "KN": "NA",
        "KM": "EU",
        "ST": "EU",
        "SK": "EU",
        "KR": "KR",
        "SI": "EU",
        "KP": "AP",
        "KW": "AP",
        "SN": "EU",
        "SM": "EU",
        "SL": "EU",
        "SC": "EU",
        "KZ": "AP",
        "KY": "NA",
        "SG": "AP",
        "SE": "EU",
        "SD": "EU",
        "DO": "NA",
        "DM": "NA",
        "DJ": "EU",
        "DK": "EU",
        "VG": "NA",
        "DE": "EU",
        "YE": "AP",
        "DZ": "EU",
        "US": "NA",
        "UY": "LATAM",
        "YT": "EU",
        "UM": "AP",
        "LB": "AP",
        "LC": "NA",
        "LA": "AP",
        "TV": "AP",
        "TW": "AP",
        "TT": "NA",
        "TR": "EU",
        "LK": "AP",
        "LI": "EU",
        "LV": "EU",
        "TO": "AP",
        "LT": "EU",
        "LU": "EU",
        "LR": "EU",
        "LS": "EU",
        "TH": "AP",
        "TF": "AN",
        "TG": "EU",
        "TD": "EU",
        "TC": "NA",
        "LY": "EU",
        "VA": "EU",
        "VC": "NA",
        "AE": "AP",
        "AD": "EU",
        "AG": "NA",
        "AI": "NA",
        "VI": "NA",
        "IS": "EU",
        "IR": "AP",
        "AM": "AP",
        "AL": "EU",
        "AO": "EU",
        "AQ": "AN",
        "AP": "AP",
        "AR": "LATAM",
        "AU": "AP",
        "AT": "EU",
        "AW": "NA",
        "IN": "AP",
        "AX": "EU",
        "AZ": "AP",
        "IE": "EU",
        "ID": "AP",
        "UA": "EU",
        "QA": "AP",
        "MZ": "EU"
    }

    A2TOA3={
        'AFG':'AF',
        'ALA':'AX',
        'ALB':'AL',
        'DZA':'DZ',
        'ASM':'AS',
        'AND':'AD',
        'AGO':'AO',
        'AIA':'AI',
        'ATA':'AQ',
        'ATG':'AG',
        'ARG':'AR',
        'ARM':'AM',
        'ABW':'AW',
        'AUS':'AU',
        'AUT':'AT',
        'AZE':'AZ',
        'BHS':'BS',
        'BHR':'BH',
        'BGD':'BD',
        'BRB':'BB',
        'BLR':'BY',
        'BEL':'BE',
        'BLZ':'BZ',
        'BEN':'BJ',
        'BMU':'BM',
        'BTN':'BT',
        'BOL':'BO',
        'BES':'BQ',
        'BIH':'BA',
        'BWA':'BW',
        'BVT':'BV',
        'BRA':'BR',
        'IOT':'IO',
        'BRN':'BN',
        'BGR':'BG',
        'BFA':'BF',
        'BDI':'BI',
        'CPV':'CV',
        'KHM':'KH',
        'CMR':'CM',
        'CAN':'CA',
        'CYM':'KY',
        'CAF':'CF',
        'TCD':'TD',
        'CHL':'CL',
        'CHN':'CN',
        'CXR':'CX',
        'CCK':'CC',
        'COL':'CO',
        'COM':'KM',
        'COG':'CG',
        'COD':'CD',
        'COK':'CK',
        'CRI':'CR',
        'CIV':'CI',
        'HRV':'HR',
        'CUB':'CU',
        'CUW':'CW',
        'CYP':'CY',
        'CZE':'CZ',
        'DNK':'DK',
        'DJI':'DJ',
        'DMA':'DM',
        'DOM':'DO',
        'ECU':'EC',
        'EGY':'EG',
        'SLV':'SV',
        'GNQ':'GQ',
        'ERI':'ER',
        'EST':'EE',
        'SWZ':'SZ',
        'ETH':'ET',
        'FLK':'FK',
        'FRO':'FO',
        'FJI':'FJ',
        'FIN':'FI',
        'FRA':'FR',
        'GUF':'GF',
        'PYF':'PF',
        'ATF':'TF',
        'GAB':'GA',
        'GMB':'GM',
        'GEO':'GE',
        'DEU':'DE',
        'GHA':'GH',
        'GIB':'GI',
        'GRC':'GR',
        'GRL':'GL',
        'GRD':'GD',
        'GLP':'GP',
        'GUM':'GU',
        'GTM':'GT',
        'GGY':'GG',
        'GIN':'GN',
        'GNB':'GW',
        'GUY':'GY',
        'HTI':'HT',
        'HMD':'HM',
        'VAT':'VA',
        'HND':'HN',
        'HKG':'HK',
        'HUN':'HU',
        'ISL':'IS',
        'IND':'IN',
        'IDN':'ID',
        'IRN':'IR',
        'IRQ':'IQ',
        'IRL':'IE',
        'IMN':'IM',
        'ISR':'IL',
        'ITA':'IT',
        'JAM':'JM',
        'JPN':'JP',
        'JEY':'JE',
        'JOR':'JO',
        'KAZ':'KZ',
        'KEN':'KE',
        'KIR':'KI',
        'PRK':'KP',
        'KOR':'KR',
        'KWT':'KW',
        'KGZ':'KG',
        'LAO':'LA',
        'LVA':'LV',
        'LBN':'LB',
        'LSO':'LS',
        'LBR':'LR',
        'LBY':'LY',
        'LIE':'LI',
        'LTU':'LT',
        'LUX':'LU',
        'MAC':'MO',
        'MDG':'MG',
        'MWI':'MW',
        'MYS':'MY',
        'MDV':'MV',
        'MLI':'ML',
        'MLT':'MT',
        'MHL':'MH',
        'MTQ':'MQ',
        'MRT':'MR',
        'MUS':'MU',
        'MYT':'YT',
        'MEX':'MX',
        'FSM':'FM',
        'MDA':'MD',
        'MCO':'MC',
        'MNG':'MN',
        'MNE':'ME',
        'MSR':'MS',
        'MAR':'MA',
        'MOZ':'MZ',
        'MMR':'MM',
        'NAM':'NA',
        'NRU':'NR',
        'NPL':'NP',
        'NLD':'NL',
        'NCL':'NC',
        'NZL':'NZ',
        'NIC':'NI',
        'NER':'NE',
        'NGA':'NG',
        'NIU':'NU',
        'NFK':'NF',
        'MKD':'MK',
        'MNP':'MP',
        'NOR':'NO',
        'OMN':'OM',
        'PAK':'PK',
        'PLW':'PW',
        'PSE':'PS',
        'PAN':'PA',
        'PNG':'PG',
        'PRY':'PY',
        'PER':'PE',
        'PHL':'PH',
        'PCN':'PN',
        'POL':'PL',
        'PRT':'PT',
        'PRI':'PR',
        'QAT':'QA',
        'REU':'RE',
        'ROU':'RO',
        'RUS':'RU',
        'RWA':'RW',
        'BLM':'BL',
        'SHN':'SH',
        'KNA':'KN',
        'LCA':'LC',
        'MAF':'MF',
        'SPM':'PM',
        'VCT':'VC',
        'WSM':'WS',
        'SMR':'SM',
        'STP':'ST',
        'SAU':'SA',
        'SEN':'SN',
        'SRB':'RS',
        'SYC':'SC',
        'SLE':'SL',
        'SGP':'SG',
        'SXM':'SX',
        'SVK':'SK',
        'SVN':'SI',
        'SLB':'SB',
        'SOM':'SO',
        'ZAF':'ZA',
        'SGS':'GS',
        'SSD':'SS',
        'ESP':'ES',
        'LKA':'LK',
        'SDN':'SD',
        'SUR':'SR',
        'SJM':'SJ',
        'SWE':'SE',
        'CHE':'CH',
        'SYR':'SY',
        'TWN':'TW',
        'TJK':'TJ',
        'TZA':'TZ',
        'THA':'TH',
        'TLS':'TL',
        'TGO':'TG',
        'TKL':'TK',
        'TON':'TO',
        'TTO':'TT',
        'TUN':'TN',
        'TUR':'TR',
        'TKM':'TM',
        'TCA':'TC',
        'TUV':'TV',
        'UGA':'UG',
        'UKR':'UA',
        'ARE':'AE',
        'GBR':'GB',
        'USA':'US',
        'UMI':'UM',
        'URY':'UY',
        'UZB':'UZ',
        'VUT':'VU',
        'VEN':'VE',
        'VNM':'VN',
        'VGB':'VG',
        'VIR':'VI',
        'WLF':'WF',
        'ESH':'EH',
        'YEM':'YE',
        'ZMB':'ZM',
        'ZWE':'ZW',
    }

    USER_AGENT = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36"}
    CLIENTPLATFORM = 'ew0KCSJwbGF0Zm9ybVR5cGUiOiAiUEMiLA0KCSJwbGF0Zm9ybU9TIjogIldpbmRvd3MiLA0KCSJwbGF0\
Zm9ybU9TVmVyc2lvbiI6ICIxMC4wLjE5MDQyLjEuMjU2LjY0Yml0IiwNCgkicGxhdGZvcm1DaGlwc2V0IjogIlVua25vd24iDQp9'
    
    CIPHERS = [
	'ECDHE-ECDSA-AES128-GCM-SHA256',
	'ECDHE-ECDSA-CHACHA20-POLY1305',
	'ECDHE-RSA-AES128-GCM-SHA256',
	'ECDHE-RSA-CHACHA20-POLY1305',
	'ECDHE+AES128',
	'RSA+AES128',
	'ECDHE+AES256',
	'RSA+AES256',
	'ECDHE+3DES',
	'RSA+3DES'
    ]
    AUTH_URL = "https://auth.riotgames.com/api/v1/authorization"
    REGION_URL = 'https://riot-geo.pas.si.riotgames.com/pas/v1/product/valorant'
    VERIFED_URL = "https://email-verification.riotgames.com/api/v1/account/status"
    ENTITLEMENT_URL = 'https://entitlements.auth.riotgames.com/api/token/v1'
    USERINFO_URL = "https://auth.riotgames.com/userinfo"
    RIOTCLIENT = ''
    ICONURL = 'https://media.valorant-api.com/weaponskins/{}/displayicon.png'
    ICONURL2 = 'https://media.valorant-api.com/weaponskinlevels/{}/displayicon.png'